---
# handlers file for redops.nodejs

- name: Restart NGINX
  systemd: "name=nginx state=restarted"

- name: Stop NGINX
  systemd: "name=nginx state=stopped"

- name: Start NGINX
  systemd: "name=nginx state=started"

- name: Enable NGINX
  systemd: "name=nginx enabled=yes"